# Taller: Auditoría de Desempeño para Negocios Digitales:

## Parte 1: Análisis de datos sintéticos

En esta parte vamos a analizar un dataset de transacciones y determinar si la estrategia de M-Commerce (App Móvil) es más rentable que el E-Commerce tradicional (Web Desktop).

Vamos a generar una base de datos aleatoria, que simula la salida de un TPS.

In [2]:
import pandas as pd
import numpy as np

# Generar datos simulados
data = {
    'ID_Transaccion': range(1001, 1051),
    'Canal': np.random.choice(['Web Desktop', 'App Móvil'], 50, p=[0.4, 0.6]),
    'Metodo_Pago': np.random.choice(['Tarjeta Crédito', 'PayPal', 'Transferencia'], 50),
    'Total_Venta': np.random.randint(20, 500, 50), # Ventas entre $20 y $500
    'Categoria': np.random.choice(['Electrónica', 'Moda', 'Hogar'], 50)
}

df = pd.DataFrame(data)

df

    ID_Transaccion        Canal      Metodo_Pago  Total_Venta    Categoria
0             1001  Web Desktop    Transferencia          235         Moda
1             1002    App Móvil           PayPal          312         Moda
2             1003    App Móvil           PayPal          118  Electrónica
3             1004    App Móvil           PayPal          191         Moda
4             1005  Web Desktop           PayPal          379  Electrónica
5             1006  Web Desktop           PayPal          233  Electrónica
6             1007  Web Desktop           PayPal          494         Moda
7             1008    App Móvil    Transferencia           54         Moda
8             1009    App Móvil    Transferencia          468         Moda
9             1010    App Móvil           PayPal          246        Hogar
10            1011  Web Desktop    Transferencia          120         Moda
11            1012    App Móvil  Tarjeta Crédito          450        Hogar
12            1013    App Móvil           PayPal          481  Electrónica
13            1014  Web Desktop  Tarjeta Crédito          150        Hogar
14            1015  Web Desktop  Tarjeta Crédito          276         Moda
15            1016  Web Desktop           PayPal           24  Electrónica
16            1017  Web Desktop    Transferencia          237  Electrónica
17            1018    App Móvil  Tarjeta Crédito          274  Electrónica
18            1019    App Móvil           PayPal          417        Hogar
19            1020  Web Desktop  Tarjeta Crédito          378         Moda
20            1021    App Móvil  Tarjeta Crédito          302  Electrónica
21            1022  Web Desktop  Tarjeta Crédito          412  Electrónica
22            1023  Web Desktop  Tarjeta Crédito          226  Electrónica
23            1024  Web Desktop    Transferencia           34        Hogar
24            1025    App Móvil  Tarjeta Crédito          365        Hogar
25            1026    App Móvil  Tarjeta Crédito           61         Moda
26            1027  Web Desktop  Tarjeta Crédito          399        Hogar
27            1028    App Móvil    Transferencia          480  Electrónica
28            1029    App Móvil  Tarjeta Crédito          198         Moda
29            1030  Web Desktop  Tarjeta Crédito           82  Electrónica
30            1031    App Móvil    Transferencia          371  Electrónica
31            1032  Web Desktop    Transferencia          250        Hogar
32            1033  Web Desktop    Transferencia          260         Moda
33            1034    App Móvil  Tarjeta Crédito           71        Hogar
34            1035    App Móvil    Transferencia          115        Hogar
35            1036    App Móvil    Transferencia          407         Moda
36            1037  Web Desktop  Tarjeta Crédito          241  Electrónica
37            1038  Web Desktop    Transferencia          426  Electrónica
38            1039    App Móvil  Tarjeta Crédito          250         Moda
39            1040    App Móvil           PayPal          256  Electrónica
40            1041  Web Desktop    Transferencia          162         Moda
41            1042    App Móvil           PayPal          190         Moda
42            1043  Web Desktop  Tarjeta Crédito           48        Hogar
43            1044    App Móvil    Transferencia           55         Moda
44            1045  Web Desktop  Tarjeta Crédito           32        Hogar
45            1046    App Móvil           PayPal          179  Electrónica
46            1047  Web Desktop  Tarjeta Crédito          346  Electrónica
47            1048    App Móvil    Transferencia          206  Electrónica
48            1049    App Móvil    Transferencia          262  Electrónica
49            1050  Web Desktop           PayPal          105        Hogar

### ¿Qué preguntas deberíamos plantearnos para obtener las respuestas que buscamos?

Buscamos saber cuál de las dos estrategias (M-Commerce o E-Commerce) es la más rentable.

Vamos a crear 4 KPIs para un MIS que nos permitan responder esta pregunta.

## Parte 2: KPIs para E-Commerce

Para esta parte vamos a utilizar los datos qu se encuentran en el repositorio en `/data/ecommerce.zip`

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../data/ecommerce.zip')
data

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

### 1. KPIs de Gestión de Logística y Operaciones (Shipment & Warehouse)

Permiten medir la eficiencia en la distribución de los productos electrónicos.

1.1. **Costo Promedio de Envío por Modo de Transporte (Mode of Shipment):** Ayuda a evaluar qué canales (Barco, Avión, Carretera) representan un mayor impacto financiero en relación con el peso del producto.

1.2. **Volumen de Ocupación por Bloque de Bodega (Warehouse Block):** Porcentaje o cantidad total de productos/peso administrados en cada bloque (A, B, C, D, E) para entender la carga operativa de la infraestructura.

1.3. **Peso Promedio del Producto por Modo de Envío:** Para analizar si se está optimizando la logística (ej. si los productos más pesados se están enviando por barco o si se está gastando de más enviándolos por avión).

### 2. KPIs de Gestión Comercial y Financiera (Sales & Revenue)

Enfocados en el rendimiento del dinero, los descuentos y la estrategia de precios.

2.1. **Ingreso Total Bruto y Costo Promedio del Producto:** Suma y promedio de la variable `Cost of the product` para entender el ticket promedio de la tienda de electrónica.

2.2. **Porcentaje de Descuento Promedio Otorgado:** Evaluar el impacto de la estrategia de promociones (`Discount offered`) y si los descuentos altos realmente correlacionan con clientes de mayor prioridad o compras previas.

2.3. **Margen Teórico Relativo por Importancia del Producto:** Cruzar `Product importance` (Low, Medium, High) con el costo para ver si los productos catalogados como "alta importancia" son también los más costosos o los que reciben más descuentos.

### 3. KPIs de Experiencia y Fidelización del Cliente (Customer Experience - CX)

Diseñados para evaluar la satisfacción y la carga de soporte post-venta.

3.1. **Índice de Satisfacción del Cliente (CSAT) Promedio:** El promedio de la variable `Customer rating` (escala 1 a 5). Se puede segmentar por género o por bloque de bodega para ver si hay anomalías.

3.2. **Tasa de Retención / Clientes Recurrentes:** Analizar la distribución de `Prior purchases` para determinar qué porcentaje de la base de datos son clientes nuevos (0-1 compras previas) vs. clientes fidelizados (2 o más compras).

3.3. **Carga de Soporte por Cliente (Customer Care Calls):** Promedio de llamadas de consulta realizadas. Permite analizar si a mayor costo del producto o menores calificaciones, aumentan las llamadas de reclamo.